### PR TITLE
Rename: add 'test' word

### PR DESCRIPTION
**Pull request by Mineru98**

### CODE REVIEW

**Comment by XahidEx** [comment]
Bro, can you get the id of the username `xahidex`? I was having issues.

**Comment by Mineru98** [comment]
> xahidex

who is that?

**Comment by Mineru98** [comment]
> Bro, can you get the id of the username `xahidex`? I was having issues. 

who is that?

**Comment by XahidEx** [comment]
> > Bro, can you get the id of the username `xahidex`? I was having issues.
> 
> who is that?

It's me! 😅

**Comment by XahidEx** [comment]
I got it!!! Don't need 😅

**Comment by junhoyeo** [comment]
Oh thanks!

**Pull request merged**
