### PR TITLE
Updated README.md to add my project details

### PR DESCRIPTION
**Pull request by AayushGithub**
Hi @junhoyeo.

First off, I just wanted to thank you so much for your continuous and excellent work on the Threads.net unofficial API. I am truly amazed with the speed with which you are pushing out incredibly useful updates.

I have just created two projects using your API and would love to be featured alongside the others on the page. 

Please do look into my request. I would be happy to provide any information that you may need.

Little bit about the projects:

### [Fortune Cookie Bot](https://www.threads.net/@fortune_cookie_bot)
<p align="center">

</p>

The Fortune Cookie Bot is one of the projects within the Threads-Projects repository. The motivation behind this project is to provide Threads.net users with valuable insights and a daily dose of wisdom. The bot leverages the [Advice Slip API](https://api.adviceslip.com/advice) to fetch interesting advice and pairs it with a random image from various sources. The bot then posts the advice and the corresponding image on Meta's Threads.net platform.

### [OPT Timeline Bot](https://www.threads.net/@opttimeline)

<p align="center">
  
</p>

The OPT Timeline Bot is another project within the Threads-Projects repository. This project addresses the need to track F1 OPT case statuses efficiently. It accomplishes this by scraping the [OPT Timeline](https://opttimeline.com/IOE?CASE_TY=EAD) website and posting updates on Meta's Threads.net platform.

### CODE REVIEW

**Comment by AayushGithub** [comment]
@junhoyeo I have Added a new Project called Thread Count
It generates markdown compatible status badges based on your Threads Follower Count.
Would love for you to check it out
https://github.com/AayushGithub/threads-projects/tree/main/thread-count

Example:
<a href="https://www.threads.net/@_junhoyeo">_junhoyeo Badge</a>

**Review by junhoyeo — APPROVED** [review]
Super! You can add screenshots too if you want!

**Comment by junhoyeo** [comment]
> @junhoyeo I have Added a new Project called Thread Count It generates markdown compatible status badges based on your Threads Follower Count. Would love for you to check it out https://github.com/AayushGithub/threads-projects/tree/main/thread-count
> 
> Example: [_junhoyeo Badge](https://www.threads.net/@_junhoyeo)

Lol I really like the badges

**Comment by AayushGithub** [comment]
Thanks @junhoyeo . I'm glad you like the badges. Please do you use them as you see fit!
I'll make a new PR with screenshots. I have also separated Thread Count into its own repo

**Pull request merged**
